version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/flask-health-docker/
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5429:5432"
    expose:
      - "5429"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flask_health_docker_db
      - POSTGRES_USER=taras_docker
      - POSTGRES_PASSWORD=taras_docker

volumes:
  db_volume: